# tomcat
server:
  port: 8003

# eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka-server:1001/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# spring
spring:
  application:
    name: service-product

  # database
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver

  # redis
  redis:
    database: 0
    host: ${redis.address}
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1

  # rabbitmq
  rabbitmq:
    host: ${rabbitmq.address}
    port: 5672
    username: guest
    password: guest

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.d2c.*.*.model
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
    sql-parser-cache: true
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    cache-enabled: false
